kola/test: disable tests that won't work with docker 20.10
These tests are 'docker.oldclient' and 'google.kubernetes.basic.docker.*'.

'docker.oldclient' tries to run docker cli 1.9 against daemon in the
image, and fails with:

  --- FAIL: docker.oldclient (29.22s)
          cluster.go:117: Error response from daemon: 400 Bad Request: malformed Host header
          cluster.go:130: "/home/core/docker-1.9.1 run echo echo 'IT WORKED'" failed: output , status Process exited with status 1

This is related to https://github.com/moby/moby/pull/39076, merged into
20.10 which removed some backwards compatibility.

The 'google.kubernetes.basic.docker.*' tests fails with the following
message in journal:

  Jul 15 14:17:42.446942 kubelet[4663]: F0715 14:17:42.446505    4663 server.go:274] failed to run Kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"

Kubernetes release 1.19 is the first one that properly supports the unified cgroup hierarchy.
We also have other tests that test that kubernetes works (kubeadm) so we
can disable the legacy ones.

The old tests should be removed once the docker 20.10 upgrade has
propagated to all channels.

See also https://github.com/kinvolk/coreos-overlay/pull/931

Signed-off-by: Jeremi Piotrowski <jpiotrowski@microsoft.com>